admin:
  admin_user:
    pk: user_id
    columns:
      firstname:
        formatter:
          name: firstName
      lastname:
        formatter:
          name: lastName
      email:
        formatter:
          name: email
        nullColumnBeforeRun: true
        unique: true
      username:
        formatter:
          name: firstName
        nullColumnBeforeRun: true
        unique: true
      password:
        formatter:
          name: password