creditmemo:
  sales_creditmemo:
    columns:
      customer_note:
        formatter:
          name: sentence
      transaction_id:
        formatter:
          name: randomNumber
          nbDigits: 8

  sales_creditmemo_comment:
    columns:
      comment:
        formatter:
          name: sentence

  sales_creditmemo_grid:
    columns:
      customer_email:
        formatter:
          name: email
        unique: true
        nullColumnBeforeRun: true
      customer_name:
        formatter:
          name: name
      billing_name:
        formatter:
          name: name
      shipping_address:
        formatter:
          name: address
      billing_address:
        formatter:
          name: address