sales_creditmemo:
  columns:
    customer_note:
      formatter: sentence

sales_creditmemo_comment:
  columns:
    comment:
      formatter: sentence

sales_creditmemo_grid:
  columns:
    customer_email:
      formatter: email
      unique: true
      nullColumnBeforeRun: true
    customer_name:
      formatter: name
    billing_name:
      formatter: name
    shipping_address:
      formatter: address
    billing_address:
      formatter: address