customer:
  customer_entity:
    columns:
      email:
        formatter:
          name: email
        unique: true
        nullColumnBeforeRun: true
      firstname:
        formatter:
        name: firstName
      lastname:
        formatter:
          name: lastName

  customer_address_entity:
    columns:
      firstname:
        formatter:
          name: firstName
      lastname:
        formatter:
          name: lastName
      company:
        formatter:
          name: company
        optional: true
      street:
        formatter:
          name: streetAddress
      city:
        formatter:
          name: city
      postcode:
        formatter:
          name: postcode
      telephone:
        formatter:
          name: phoneNumber
      fax:
        formatter:
          name: phoneNumber
        optional: true

  customer_grid_flat:
    columns:
      name:
        formatter:
          name: name
      firstname:
        formatter:
          name: firstName
      email:
        formatter:
          name: email
        unique: true
        nullColumnBeforeRun: true
      dob:
        formatter:
          name: dateTimeThisCentury
        optional: true
      billing_full:
        formatter:
          name: address
      shipping_full:
        formatter:
          name: address
      billing_firstname:
        formatter:
          name: firstName
      billing_lastname:
        formatter:
          name: lastName
      billing_telephone:
        formatter:
          name: phoneNumber
      billing_postcode:
        formatter:
          name: postcode
      billing_street:
        formatter:
          name: streetAddress
      billing_city:
        formatter:
          name: city
      billing_fax:
        formatter:
          name: phoneNumber
        optional: true
      billing_vat_id:
        formatter:
          name: vat
        optional: true
      billing_company:
        formatter:
          name: company
        optional: true