email:
  email_contact:
    pk: email_contact_id
    columns:
      email:
        formatter:
          name: email

  email_automation:
    pk: id
    columns:
      email:
        formatter:
          name: email

  email_campaign:
    pk: id
    columns:
      email:
        formatter:
          name: email