review:
  review_detail:
    pk: detail_id
    columns:
      nickname:
        provider: \Test\WoopFormatter
        formatter: firstName
      title:
        formatter: sentence
      detail:
        formatter: paragraph