shipment:
  sales_shipment:
    columns:
      customer_note:
        formatter:
          name: sentence
        optional: true

  sales_shipment_comment:
    columns:
      comment:
        formatter:
          name: sentence
        optional: true

  sales_shipment_grid:
    columns:
      customer_email:
        formatter:
          name: email
        unique: true
        nullColumnBeforeRun: true
      customer_name:
        formatter:
          name: name
      shipping_name:
        formatter:
          name: name
      billing_name:
        formatter:
          name: name
      shipping_address:
        formatter:
          name: address
      billing_address:
        formatter:
          name: address