creditmemo:
  sales_flat_creditmemo:
    columns:
      discount_description:
        formatter:
        name: word
      transaction_id:
        formatter:

    name: randomNumber

  sales_flat_creditmemo_comment:
    columns:
      comment:
        formatter:

    name: sentence

  sales_flat_creditmemo_grid:
    columns:
      billing_name:
        formatter:
    name: name