quote:
  sales_flat_quote:
    columns:
      customer_email:
        formatter:
          name: email
          unique: true
          nullColumnBeforeRun: true
      customer_firstname:
        formatter:
        name: firstName
      customer_lastname:
        formatter:
        name: lastName
      customer_dob:
        formatter:
          name: dateTimeThisCentury
          optional: true
      customer_taxvat:
        formatter:
          name: vat
          optional: true
      remote_ip:
        formatter:
        name: ipv4
      customer_note:
        formatter:
          name: sentence
          optional: true

  sales_flat_quote_address:
    columns:
      email:
        formatter:
          name: email
          unique: true
          nullColumnBeforeRun: true
      firstname:
        formatter:
        name: firstName
      lastname:
        formatter:
        name: lastName
      company:
        formatter:
          name: company
          optional: true
      street:
        formatter:
        name: streetAddress
      city:
        formatter:
        name: city
      postcode:
        formatter:
        name: postcode
      telephone:
        formatter:
        name: phoneNumber
      fax:
        formatter:
          name: phoneNumber
          optional: true
      vat_id:
        formatter:
          name: vat
          optional: true
      customer_notes:
        formatter:
          name: sentence
          optional: true