quote:
  sales_flat_quote:
    columns:
      customer_email:
        formatter: email
        unique: true
        nullColumnBeforeRun: true
      customer_firstname:
        formatter: firstName
      customer_lastname:
        formatter: lastName
      customer_dob:
        formatter: dateTimeThisCentury
        optional: true
      customer_taxvat:
        formatter: vat
        optional: true
      remote_ip:
        formatter: ipv4
      customer_note:
        formatter: sentence
        optional: true

  sales_flat_quote_address:
    columns:
      email:
        formatter: email
        unique: true
        nullColumnBeforeRun: true
      firstname:
        formatter: firstName
      lastname:
        formatter: lastName
      company:
        formatter: company
        optional: true
      street:
        formatter: streetAddress
      city:
        formatter: city
      postcode:
        formatter: postcode
      telephone:
        formatter: phoneNumber
      fax:
        formatter: phoneNumber
        optional: true
      vat_id:
        formatter: vat
        optional: true
      customer_notes:
        formatter: sentence
        optional: true