recurring:
  sales_recurring_profile:
    columns:
      subscriber_name:
        formatter:
          name: name
      shipping_addresss_info:
        formatter:
          name: streetAddress
      billing_addresss_info:
        formatter:
          name: streetAddress